### ISSUE TITLE
Set GPT 4 + plugin as default?

### ISSUE THREAD

**Issue by chaoscreater** [n1te1337/chrome-chatgpt-default-model-selector#1]
There isn't an option to set the model to use plugins. Another extension called Superpowers ChatGPT can do this, but it's very buggy and conflicts with many other extensions or userscripts.

**Comment by n1te1337** [comment]
@chaoscreater just submitted an update to the Chrome store that will add support for this (version 1.2.0). Let me know if this is what you had in mind
